### ISSUE TITLE
Lets talk about this project

### ISSUE THREAD

**Issue by tinternet** [d0ntth1nc/Team-Satsuma#1]
ok?

**Comment by velio84** [comment]
Няколко неща от мен, които да обсъдим:
- layout на сайта - давайте предложения за цялостното представяне - как да изглежда. Аз ще се опитам да нахвърлям нещо после и ще закача снимка.
- тема на форума - предложете тема и име за сайта.
  Аз предлагам да е форум за програмиране със секции/категории -> различни езици за програмиране. Име - The Art Of Coding (примерно)

**Comment by tinternet** [comment]
Направо commit & push. На който не му харесва ще го промени :)

**Comment by velio84** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/8689825/7014520/9012a3aa-dcce-11e4-8da0-1cd48c15a6f9.png)
Бутнах някакъв супер бейсик лейаут, може да го погледнете и дооправите :)

**Comment by tinternet** [comment]
Аз направих подобрен :)

**Comment by velio84** [comment]
Very good job :+1:
