### ISSUE TITLE
Добавени 2 модела: Theme и Answer, недовършени. Трябва да се добавят и таблици в базата.

### ISSUE THREAD

**Issue by yuletodim** [d0ntth1nc/Team-Satsuma#4]

**Comment by velio84** [comment]
"На главната страница ще се отваря банер, но първо да изясним категориите и дали изобщо да има, за да се навържат семантично картинките."

според мен е добре да има категории. Ако са само на 1 ниво - нещо от сорта на:
- JavaScript
- PHP
- Girls
  и т.н. или ако са на 2 нива, нещо от сорта на:
- Programming
  \
  - JavaScript
  - Java
- Other stuff
  \
  - GIrls
  - Booze

.....

**Comment by JuliaFS** [comment]
Да, мисля че и в самото задание е посочено да има категории...От вчера
експериментирам, но като се получи нещо що годе ОК ще го кача...

2015-04-09 3:54 GMT+03:00 Velichko Golev notifications@github.com:
